{"uuid": "c6fdada6-99bf-41d7-ad82-7ba5fafc1ed3", "children": ["d5d286c6-7b8e-43d7-9d9c-a50f746f30b9"], "befores": [{"name": "country", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities\n\n", "trace": "  File \"C:\\Python_Selenium\\Selenium\\Zeptoselenium\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Python_Selenium\\Selenium\\Zeptoselenium\\.venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Python_Selenium\\Selenium\\Zeptoselenium\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python_Selenium\\Selenium\\Zeptoselenium\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python_Selenium\\Selenium\\Zeptoselenium\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Python_Selenium\\Selenium\\Zeptoselenium\\Tests\\conftest.py\", line 142, in country\n    driver = webdriver.Firefox(service=FirefoxService(GeckoDriverManager().install()), options=options)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python_Selenium\\Selenium\\Zeptoselenium\\.venv\\Lib\\site-packages\\selenium\\webdriver\\firefox\\webdriver.py\", line 71, in __init__\n    super().__init__(command_executor=executor, options=options)\n  File \"C:\\Python_Selenium\\Selenium\\Zeptoselenium\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 238, in __init__\n    self.start_session(capabilities)\n  File \"C:\\Python_Selenium\\Selenium\\Zeptoselenium\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 325, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python_Selenium\\Selenium\\Zeptoselenium\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 380, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Python_Selenium\\Selenium\\Zeptoselenium\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1730825607561, "stop": 1730825616553}], "start": 1730825607561, "stop": 1730825616789}