{"uuid": "952aee00-fe59-4820-ac7d-4f0f5c6e72d5", "children": ["f97362ef-405f-4efb-a8bc-19d47bb15299"], "befores": [{"name": "country", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found\nStacktrace:\n\tGetHandleVerifier [0x00007FF6C8BCDC65+12853]\n\tMicrosoft::Applications::Events::EventProperty::empty [0x00007FF6C8E783B4+2250276]\n\tMicrosoft::Applications::Events::EventProperty::empty [0x00007FF6C8DB7696+1460486]\n\t(No symbol) [0x00007FF6C89EF27C]\n\t(No symbol) [0x00007FF6C89EE4F0]\n\t(No symbol) [0x00007FF6C89EFFF4]\n\t(No symbol) [0x00007FF6C89E8163]\n\t(No symbol) [0x00007FF6C89BFB54]\n\t(No symbol) [0x00007FF6C89BF000]\n\t(No symbol) [0x00007FF6C89BF741]\n\tMicrosoft::Applications::Events::EventProperty::empty [0x00007FF6C8D4CDA4+1024020]\n\tMicrosoft::Applications::Events::EventProperty::~EventProperty [0x00007FF6C8AE9A04+57108]\n\tMicrosoft::Applications::Events::EventProperty::empty [0x00007FF6C8D4BDA3+1019923]\n\tMicrosoft::Applications::Events::EventProperty::empty [0x00007FF6C8D4BA09+1019001]\n\tMicrosoft::Applications::Events::ILogConfiguration::operator* [0x00007FF6C8B6E021+394913]\n\tMicrosoft::Applications::Events::ILogConfiguration::operator* [0x00007FF6C8B6A944+380868]\n\tMicrosoft::Applications::Events::ILogConfiguration::operator* [0x00007FF6C8B6AA89+381193]\n\tMicrosoft::Applications::Events::ILogConfiguration::operator* [0x00007FF6C8B62286+346374]\n\tBaseThreadInitThunk [0x00007FFDD249257D+29]\n\tRtlUserThreadStart [0x00007FFDD3A0AF08+40]\n\n", "trace": "  File \"C:\\Python_Selenium\\Selenium\\Zeptoselenium\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Python_Selenium\\Selenium\\Zeptoselenium\\.venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Python_Selenium\\Selenium\\Zeptoselenium\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python_Selenium\\Selenium\\Zeptoselenium\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python_Selenium\\Selenium\\Zeptoselenium\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Python_Selenium\\Selenium\\Zeptoselenium\\Tests\\conftest.py\", line 163, in country\n    driver = webdriver.Edge(service=EdgeService(EdgeChromiumDriverManager().install()), options=options)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python_Selenium\\Selenium\\Zeptoselenium\\.venv\\Lib\\site-packages\\selenium\\webdriver\\edge\\webdriver.py\", line 45, in __init__\n    super().__init__(\n  File \"C:\\Python_Selenium\\Selenium\\Zeptoselenium\\.venv\\Lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 66, in __init__\n    super().__init__(command_executor=executor, options=options)\n  File \"C:\\Python_Selenium\\Selenium\\Zeptoselenium\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 212, in __init__\n    self.start_session(capabilities)\n  File \"C:\\Python_Selenium\\Selenium\\Zeptoselenium\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 299, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python_Selenium\\Selenium\\Zeptoselenium\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Python_Selenium\\Selenium\\Zeptoselenium\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1730824594465, "stop": 1730824625822}], "start": 1730824594465, "stop": 1730824626026}