{"uuid": "63e2d247-9641-46bf-9aa3-83a4bf3b82ac", "children": ["6a2dd104-a015-4a76-b809-a061508cd85c"], "befores": [{"name": "country", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities\n\n", "trace": "  File \"C:\\Python_Selenium\\Selenium\\Zeptoselenium\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Python_Selenium\\Selenium\\Zeptoselenium\\.venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Python_Selenium\\Selenium\\Zeptoselenium\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python_Selenium\\Selenium\\Zeptoselenium\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python_Selenium\\Selenium\\Zeptoselenium\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Python_Selenium\\Selenium\\Zeptoselenium\\Tests\\conftest.py\", line 165, in country\n    driver = webdriver.Firefox(service=FirefoxService(GeckoDriverManager().install()), options=options)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python_Selenium\\Selenium\\Zeptoselenium\\.venv\\Lib\\site-packages\\selenium\\webdriver\\firefox\\webdriver.py\", line 71, in __init__\n    super().__init__(command_executor=executor, options=options)\n  File \"C:\\Python_Selenium\\Selenium\\Zeptoselenium\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 212, in __init__\n    self.start_session(capabilities)\n  File \"C:\\Python_Selenium\\Selenium\\Zeptoselenium\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 299, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python_Selenium\\Selenium\\Zeptoselenium\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Python_Selenium\\Selenium\\Zeptoselenium\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1730824654502, "stop": 1730824668289}], "start": 1730824654502, "stop": 1730824668525}